categories:
  - name: Языковая победа
    id: language
    items:
      - name: Bash
        items:
          - domain: башпобеда.рф
      - name: C
        items:
        - domain: сипобеда.рф
          comment: в процессе восстановления 
      - name: Go
        items:
          - domain: гопобеда.рф
      - name: JavaScript
        items:
          - domain: жспобеда.рф
      - name: TypeScript
        items:
          - domain: тайпскриптпобеда.рф
      - name: Lua
        items:
          - domain: луапобеда.рф
      - name: Pascal
        items:
          - domain: паскальпобеда.рф
      - name: HTML
        items:
          - domain: хтмлпобеда.рф
      - name: Elixir
        items:
          - domain: эликсирпобеда.рф
            comment: в процессе восстановления 
      - name: Python
        items:
          - domain: питонпобеда.рф
      - name: Rust
        items:
          - domain: растпобеда.рф
            comment: временно не работает 
      - name: V
        items:
          - domain: випобеда.рф
      - name: Swift
        items:
          - domain: свифтпобеда.рф
            comment: в процессе восстановления
      - name: Haskell
        items:
          - domain: хаскеллпобеда.рф
  - name: Линуксовая победа
    id: linux
    items:
      - name: Linux
        items:
          - domain: линукспобеда.рф
      - name: Arch Linux
        items:
          - domain: арчпобеда.рф
      - name: Gentoo Linux
        items:
          - domain: гентупобеда.рф
      - name: Yocto Linux
        items:
          - domain: йоктопобеда.рф
            comment: в процессе восстановления 
#  - name: СВО
#    id: svo
#    items:
  - name: Остальное
    id: other
    items:
      - name: Beget
        items:
          - domain: бегетпобеда.рф
      - name: ESP32
        items:
          - domain: есп32победа.рф
      - name: RISC-V
        items:
          - domain: рисквпобеда.рф
            comment: в процессе восстановления 
      - name: МТУСИ
        items:
          - domain: мтусипобеда.рф
      - name: Окабефон (что)
        items:
          - domain: окабефонпобеда.рф
      - name: MAX
        items:
          - domain: макспобеда.рф
            comment: работает даже на xbt573/awesome-pobeda
  - name: Поражения
    id: loses
    items:
      - name: Rust
        items:
          - domain: растпоражение.рф
      - name: Go
        items:
          - domain: гопоражение.рф
  - name: Кладбище побед
    id: graveyard
    items:
      - name: C++
        items:
          - domain: плюсыпобеда.рф
            comment: не резолвится
      - name: Java
        items:
          - domain: жавапобеда.рф
            comment: в процессе восстановления
      - name: Kotlin
        items:
          - domain: котлинпобеда.рф
            comment: не резолвится
      - name: Nix
        items:
          - domain: никспобеда.рф
            comment: домен не резолвится
      - name: Scheme
        items:
          - domain: схемапобеда.рф
            comment: более не поддерживается
      - name: svo.ru
        items:
          - domain: svo.ru
            comment: не резолвится
      - name: Магия по контракту
        items:
          - domain: магияпоконтракту.рф
            comment: 127.0.0.1
      - name: STM32
        items:
          - domain: стм32победа.рф
            comment: домен закончился
      - name: Valorant
        items:
          - domain: валорантпобеда.рф
            comment: какая нахуй рукодельница?
